[package]
name = "lichess-event-stream"
version = "0.1.0"
authors = ["ProgramFOX <programfox@hotmail.be>"]

[dependencies]
hyper = "0.12"
hyper-tls = "0.3.0"
tokio = "0.1.7"
futures = "0.1.21"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
ws = "0.7.8"